### ISSUE TITLE
Verifying derived proof fails in Browser environment

### ISSUE THREAD

**Issue by TimoGlastra** [mattrglobal/jsonld-signatures-bbs#119]
The following derived proof verifies in NodeJS (node 10, using test setup in this repo), but fails in my browser (`Brave Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (x86_64)` and also tried Google Chrome). The other operations (issue, verify, derive) work fine, so I don't think it has anything to do with my setup.

Not sure if it's helpful, but I've also attached the stack trace of the error below. 

<details>
  <summary>The derived credential</summary>
  
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3id.org/security/bbs/v1"
  ],
  "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
  "type": ["PermanentResidentCard", "VerifiableCredential"],
  "description": "Government of Example Permanent Resident Card.",
  "identifier": "83627465",
  "name": "Permanent Resident Card",
  "credentialSubject": {
    "id": "did:example:b34ca6cd37bbf23",
    "type": ["Person", "PermanentResident"],
    "givenName": "JOHN"
  },
  "expirationDate": "2029-12-03T12:19:52Z",
  "issuanceDate": "2019-12-03T12:19:52Z",
  "issuer": "did:example:489398593",
  "proof": {
    "type": "BbsBlsSignatureProof2020",
    "created": "2021-04-20T06:56:05Z",
    "nonce": "lw6Mn3vl7Se9QxB0agM2ntjN9NHkposIqPaJca4WoOxJeSnGZ5sUbePms2ijUkIpaE4=",
    "proofPurpose": "assertionMethod",
    "proofValue": "ABkB/waPib6r63rXkeHFn/xnzD+0an0dkhBNpD3Kq+1b1H3Oj7lA1sLnR9DLCaeWq18eDdyzlK/fR87PlMUt78kvu/UTcCUSIP/GNIgBJNLZF0zXDkh+pIIU9BL1rrtDBHsx1IZUtWVvmxISJ75+q4CUqUNoHaETyIZ5E6w0cGeoamI43InYDRYlC/ImgGy0kdS9BQYxAAAAdJJ8O/STiAn32OGG+Lm/EkDqcrymKOp5qvbnQenTZjB5WKDAuRw/4CngV4sU2Ftu/gAAAAI8VUYXyzwpuYPexn9nsuEgkSU1Lclgi0ObgMknUgGQ8EB4MmLwCZEkKFRFTz2lTNw+4AaItcaZ4h8UDFTGcKaosNsbPe8aPIWpgcd1i+H4KTfJLGI9JvVzJZIcWZK7CMp9kIODi49Kg/dEizp/dvrIAAAAC1QnOfssbTRJCuQXs6Ryo80Bq+bkVXd5JekGreoR10SWTpexPAQfjOhjE9cJQHNI+EWTQo3OQBEcxOKxGkdbyAYoHqz740JT7UtOUkoso2xTGC/+HBmKFrT+DiJZrUtQhTS2Eh8WZYvWuLqguLFBuDnYLsKFdvlq5PKAhS8JBIbbQJV8nwGBdPLkJabcTH035YQKfoJIDhXG+Zke6/ACYL0hqL2p8bOYO+chxxq1yRvTNzbLDKKxgh0N4fIZlOBiInHnzGso+WFIZObNUJM2dxc3eA4/QNaKYa9J5v9rTn0ZBAOmBNjUHD1ATPDAz8gPxf56Ba3VepryHVXtdtBO1Z5i5VMYEP2ODd5kgmys3lPjp88TpWqmMRpSyP4UI62CZggH+ZIxlXPavjP8OXrabODoKMqzU+Hz0fCQ64xECNA8D7o/qVKeudSKJzOoRCRgdiP5ZpSiY1sdRyW85Zj7CtE=",
    "verificationMethod": "did:example:489398593#test"
  }
}
```

</details>

<details>
  <summary>The error</summary>
  

```
Uncaught (in promise) RuntimeError: unreachable
    at <anonymous>:wasm-function[450]:0x4f76e
    at <anonymous>:wasm-function[662]:0x587c4
    at <anonymous>:wasm-function[1003]:0x5fb1b
    at <anonymous>:wasm-function[925]:0x5eb70
    at <anonymous>:wasm-function[1004]:0x5fb51
    at <anonymous>:wasm-function[745]:0x5ae01
    at <anonymous>:wasm-function[114]:0x29958
    at <anonymous>:wasm-function[646]:0x57e65
    at <anonymous>:wasm-function[234]:0x3f1eb
    at <anonymous>:wasm-function[600]:0x562d2
    at <anonymous>:wasm-function[506]:0x52410
    at _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9c9dac1409fe2461 (<anonymous>:wasm-function[1043]:0x600fb)
    at __wbg_adapter_32 (http://localhost:8000/commons.js:24746:10)
    at real (http://localhost:8000/commons.js:24731:20)
(anonymous) @ 001aa38a:0x4f76e
(anonymous) @ 001aa38a:0x587c4
(anonymous) @ 001aa38a:0x5fb1b
(anonymous) @ 001aa38a:0x5eb70
(anonymous) @ 001aa38a:0x5fb51
(anonymous) @ 001aa38a:0x5ae01
(anonymous) @ 001aa38a:0x29958
(anonymous) @ 001aa38a:0x57e65
(anonymous) @ 001aa38a:0x3f1eb
(anonymous) @ 001aa38a:0x562d2
(anonymous) @ 001aa38a:0x52410
_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9c9dac1409fe2461 @ 001aa38a:0x600fb
__wbg_adapter_32 @ wasm.js:180
real @ wasm.js:165
Promise.then (async)
../@mattrglobal/bbs-signatures/lib/wasm.js.module.exports.__wbg_then_4a7a614abbbe6d81 @ wasm.js:576
(anonymous) @ 001aa38a:0x58680
(anonymous) @ 001aa38a:0x5c05a
(anonymous) @ 001aa38a:0x4ff6b
(anonymous) @ 001aa38a:0x4a9f0
wasm_bindgen__convert__closures__invoke2_mut__h1b8f593dd423e948 @ 001aa38a:0x600a2
__wbg_adapter_96 @ wasm.js:360
cb0 @ wasm.js:558
../@mattrglobal/bbs-signatures/lib/wasm.js.module.exports.__wbg_new_d0c63652ab4d825c @ wasm.js:563
(anonymous) @ 001aa38a:0x608ba
(anonymous) @ 001aa38a:0x5a2d1
blsVerifyProof @ 001aa38a:0x5f2ed
../@mattrglobal/bbs-signatures/lib/wasm.js.module.exports.blsVerifyProof @ wasm.js:341
../@mattrglobal/bbs-signatures/lib/index.js.module.exports.blsVerifyProof @ index.js:127
async function (async)
../@mattrglobal/bbs-signatures/lib/index.js.module.exports.blsVerifyProof @ index.js:126
verifyProof @ BbsBlsSignatureProof2020.js:217
async function (async)
verifyProof @ BbsBlsSignatureProof2020.js:184
(anonymous) @ ProofSet.js:323
async function (async)
(anonymous) @ ProofSet.js:322
_verify @ ProofSet.js:320
async function (async)
_verify @ ProofSet.js:311
verify @ ProofSet.js:248
async function (async)
verify @ ProofSet.js:243
verify @ jsonld-signatures.js:111
_verifyCredential @ vc.js:271
verifyCredential @ vc.js:222
_callee4$ @ issue.js:48
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_verifyDerived @ issue.js:48
verifyDerived @ issue.js:48
_callee2$ @ BbsComponent.js:90
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_deriveCredential @ BbsComponent.js:89
deriveCredential @ BbsComponent.js:89
(anonymous) @ BbsComponent.js:117
commitHookEffectListMount @ react-dom.development.js:19732
commitPassiveHookEffects @ react-dom.development.js:19770
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
flushPassiveEffectsImpl @ react-dom.development.js:22854
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
flushPassiveEffects @ react-dom.development.js:22821
performSyncWorkOnRoot @ react-dom.development.js:21738
(anonymous) @ react-dom.development.js:11090
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
flushSyncCallbackQueueImpl @ react-dom.development.js:11085
flushSyncCallbackQueue @ react-dom.development.js:11073
unbatchedUpdates @ react-dom.development.js:21910
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24758
render @ react-dom.development.js:24841
(anonymous) @ app.js:165
setTimeout (async)
(anonymous) @ ready.js:37
(anonymous) @ app.js:160
Promise.then (async)
(anonymous) @ app.js:153
Promise.then (async)
(anonymous) @ app.js:43
./.cache/app.js @ app.js:38
__webpack_require__ @ bootstrap:832
fn @ bootstrap:129
0 @ index.js:3
__webpack_require__ @ bootstrap:832
(anonymous) @ bootstrap:972
(anonymous) @ bootstrap:972
```

</details>

To add some extra context. I'm using `vc-js`, but it seems like this has nothing to do with it. It fails on the lower level WASM operation. I'm using the same versions in my browser environment of libraries as used in the tests of this repo.

```ts
  const result = await vc.verifyCredential({
    credential: {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/citizenship/v1",
        "https://w3id.org/security/bbs/v1",
      ],
      id: "https://issuer.oidp.uscis.gov/credentials/83627465",
      type: ["PermanentResidentCard", "VerifiableCredential"],
      description: "Government of Example Permanent Resident Card.",
      identifier: "83627465",
      name: "Permanent Resident Card",
      credentialSubject: {
        id: "did:example:b34ca6cd37bbf23",
        type: ["Person", "PermanentResident"],
        givenName: "JOHN",
      },
      expirationDate: "2029-12-03T12:19:52Z",
      issuanceDate: "2019-12-03T12:19:52Z",
      issuer: "did:example:489398593",
      proof: {
        type: "BbsBlsSignatureProof2020",
        created: "2021-04-20T06:56:05Z",
        nonce:
          "lw6Mn3vl7Se9QxB0agM2ntjN9NHkposIqPaJca4WoOxJeSnGZ5sUbePms2ijUkIpaE4=",
        proofPurpose: "assertionMethod",
        proofValue:
          "ABkB/waPib6r63rXkeHFn/xnzD+0an0dkhBNpD3Kq+1b1H3Oj7lA1sLnR9DLCaeWq18eDdyzlK/fR87PlMUt78kvu/UTcCUSIP/GNIgBJNLZF0zXDkh+pIIU9BL1rrtDBHsx1IZUtWVvmxISJ75+q4CUqUNoHaETyIZ5E6w0cGeoamI43InYDRYlC/ImgGy0kdS9BQYxAAAAdJJ8O/STiAn32OGG+Lm/EkDqcrymKOp5qvbnQenTZjB5WKDAuRw/4CngV4sU2Ftu/gAAAAI8VUYXyzwpuYPexn9nsuEgkSU1Lclgi0ObgMknUgGQ8EB4MmLwCZEkKFRFTz2lTNw+4AaItcaZ4h8UDFTGcKaosNsbPe8aPIWpgcd1i+H4KTfJLGI9JvVzJZIcWZK7CMp9kIODi49Kg/dEizp/dvrIAAAAC1QnOfssbTRJCuQXs6Ryo80Bq+bkVXd5JekGreoR10SWTpexPAQfjOhjE9cJQHNI+EWTQo3OQBEcxOKxGkdbyAYoHqz740JT7UtOUkoso2xTGC/+HBmKFrT+DiJZrUtQhTS2Eh8WZYvWuLqguLFBuDnYLsKFdvlq5PKAhS8JBIbbQJV8nwGBdPLkJabcTH035YQKfoJIDhXG+Zke6/ACYL0hqL2p8bOYO+chxxq1yRvTNzbLDKKxgh0N4fIZlOBiInHnzGso+WFIZObNUJM2dxc3eA4/QNaKYa9J5v9rTn0ZBAOmBNjUHD1ATPDAz8gPxf56Ba3VepryHVXtdtBO1Z5i5VMYEP2ODd5kgmys3lPjp88TpWqmMRpSyP4UI62CZggH+ZIxlXPavjP8OXrabODoKMqzU+Hz0fCQ64xECNA8D7o/qVKeudSKJzOoRCRgdiP5ZpSiY1sdRyW85Zj7CtE=",
        verificationMethod: "did:example:489398593#test",
      },
    },
    documentLoader: customLoader,
    suite: new BbsBlsSignatureProof2020(),
  });
```

**Comment by kdenhartog** [comment]
Yeah this is an issue we discovered that we haven't had the time to completely debug yet. For some reason the browser's WASM engine doesn't like the compiled WASM files from the underlying BBS Signatures library. Issue #102 is caused by similar related aspects of the browser's WASM engine. For some reason the Node.js implementation works well with this repository but none of the browsers like it. I normally run Firefox and that engine has produced similar concerns.

If you get time to dig into it further please post back. Otherwise @tplooker  or I will take a look at it when we get some time.

**Comment by kuzdogan** [comment]
I can also confirm the issue. In my case, however, I was able to successfully verify some of the derived proofs. I wasn't able to recognize a pattern on what gets verified and what throws an error. Still leaving some of them here in case it helps. I can provide further details.

For the (non-derived) credential below, only removing `journal`, or removing none of the fields when deriving a proof results in a successful verification. All other combinations I tried threw the same error. The same type of credential with different `firstName`, `journal` etc. fields also behave the same. 
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://raw.githubusercontent.com/kuzdogan/peer-review-verifiable-credentials-thesis/main/code/PeerReview.json",
    "https://w3id.org/security/bbs/v1"
  ],
  "id": "http://localhost:3000/v1/auth/reviews/609ac62276bfdce844d8ee6c/credential",
  "type": [
    "VerifiableCredential",
    "PeerReviewCredential"
  ],
  "description": "Peer Review Credential version 0.1",
  "issuer": "did:example:489398593",
  "issuanceDate": "2021-05-12T01:02:28.061Z",
  "credentialSubject": {
    "id": "http://localhost:3000/v1/auth/users/609ac62276bfdce844d8ee6c",
    "type": "PeerReview",
    "name": "Peer Review: Studying the prominence effect amid the COVID-19 crisis: implications for public health policy decision-making.",
    "journal": "Journal X",
    "author": {
      "type": "PeerReviewAuthor",
      "id": "http://localhost:3000/v1/auth/users/609abf01d63387cc91df415d",
      "givenName": "test",
      "familyName": "test",
      "email": "alice@test.com"
    }
  },
  "proof": {
    "type": "BbsBlsSignature2020",
    "created": "2021-05-12T01:02:28Z",
    "proofPurpose": "assertionMethod",
    "proofValue": "tMLj5nG8l55+cNFFDs3MBIxVKvM8BlQgYiW31uuPPEHLCwSIFO0NFfkMEWYnqH2xLD6XJtPxvT/oCP/Z7vyoPMGXJo2dgisA5zCciowGjrQFE71kI2STDiShD1oMtC6RhDM67OR1YqX3k85ltKTgkQ==",
    "verificationMethod": "did:example:489398593#test"
  }
}
```

The resulting derived credential when `journal` is excluded
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://raw.githubusercontent.com/kuzdogan/peer-review-verifiable-credentials-thesis/main/code/PeerReview.json",
    "https://w3id.org/security/bbs/v1"
  ],
  "id": "http://localhost:3000/v1/auth/reviews/609ac62276bfdce844d8ee6c/credential",
  "type": [
    "PeerReviewCredential",
    "VerifiableCredential"
  ],
  "description": "Peer Review Credential version 0.1",
  "credentialSubject": {
    "id": "http://localhost:3000/v1/auth/users/609ac62276bfdce844d8ee6c",
    "type": "PeerReview",
    "name": "Peer Review: Studying the prominence effect amid the COVID-19 crisis: implications for public health policy decision-making.",
    "author": {
      "id": "http://localhost:3000/v1/auth/users/609abf01d63387cc91df415d",
      "type": "PeerReviewAuthor",
      "email": "alice@test.com",
      "familyName": "test",
      "givenName": "test"
    }
  },
  "issuanceDate": "2021-05-12T01:02:28.061Z",
  "issuer": "did:example:489398593",
  "proof": {
    "type": "BbsBlsSignatureProof2020",
    "created": "2021-05-12T01:02:28Z",
    "nonce": "i+fAsvM8YIfLerh52uDEdsoJhE7CeIzZWbBgKZh9CyGcqlmeXZfVVSrTicK43/7OLVU=",
    "proofPurpose": "assertionMethod",
    "proofValue": "ABIB//+qF9WBiBeEqJ+joLCPHhBiAQulmj80Y+3hscI0UGqDP+Rw9qPzqOEuEMa5/ftYaoGglAm5kOjua5pOhyNa97+mtco/WyWXnGWXNBFZVYDCpZOiFpJ/2VwJq0qlvq2sRCSWk1GMJ2A5FOC1Dy3B1vcV2a26Z+DSkTd3tdks7eYs7anwikZhB2OI66glpvscpN4AAAB0i7yt6QSEGcKL79dvK8D9B04JS4EqSq0aC39OZJcuXs2mqK4RdW7ksks5jWPN1PJPAAAAAiqXOh7GEyOZ//iTJ9eUA/XmPCi3xqGjLBS5L/8hLTSdPdHKcPJh33wiOuURo9Muco7WiPywwKOki5gRnsbE0RyDGvxUEeUzX1L9kB75vSHH6YwT9s+3oDacVe2jGbG5bOhB6iw2FBlhy8WOQb/M7A0AAAADGPkP0JxTv7VnAHlsM/LJf9EvQJWas/zidPrBofQferw0XxrMS1WZNiLmHvUKR8XlJuNI9Ib2R4A/cSNJGQN4YEJXjy9vN7Ki21UXiOqAwQtCCACsJLQ76PLqiQM0VIzH",
    "verificationMethod": "did:example:489398593#test"
  }
}
```


The underlying custom context file is this. Might contain errors, feel free to point out.
```
{
  "@context": {
    "@version": 1.1,
    "@protected": true,
    "name": "http://schema.org/name",
    "description": "http://schema.org/description",
    "identifier": "http://schema.org/identifier",
    "image": "http://schema.org/image",
    "PeerReviewCredential": {
      "@id": "https://raw.githubusercontent.com/kuzdogan/peer-review-verifiable-credentials-thesis/main/code/PeerReviewVC.json#PeerReviewCredential",
      "@context": {
        "@version": 1.1,
        "@protected": true,
        "id": "@id",
        "type": "@type",
        "description": "http://schema.org/description",
        "name": "http://schema.org/name",
        "identifier": "http://schema.org/identifier"
      }
    },
    "PeerReview": {
      "@id": "https://raw.githubusercontent.com/kuzdogan/peer-review-verifiable-credentials-thesis/main/code/PeerReviewVC.json#PeerReview",
      "@context": {
        "@version": 1.1,
        "@protected": true,
        "id": "@id",
        "type": "@type",
        "description": "http://schema.org/description",
        "name": "http://schema.org/name",
        "identifier": "http://schema.org/identifier",
        "author": "https://raw.githubusercontent.com/kuzdogan/peer-review-verifiable-credentials-thesis/main/code/PeerReviewVC.json#author",
        "journal": "https://schema.org/Periodical"
      }
    },
    "PeerReviewAuthor": {
      "@id": "https://raw.githubusercontent.com/kuzdogan/peer-review-verifiable-credentials-thesis/main/code/PeerReviewVC.json#PeerReviewAuthor",
      "@context": {
        "@version": 1.1,
        "@protected": true,
        "id": "@id",
        "type": "@type",
        "givenName": "https://schema.org/givenName",
        "familyName": "https://schema.org/familyName",
        "email": "https://schema.org/email",
        "identifier": "http://schema.org/identifier"
      }
    }
  }
}
```

**Comment by kdenhartog** [comment]
Thanks more examples like this will be helpful when we get around to looking at it. Also, side note cool idea to host the contexts on githubusercontent.com

**Comment by kuzdogan** [comment]
So I moved the verification to the server-side, and really interestingly it started to throw exactly the same error after an upgrade to node.js version `v14.17.0` (LTS) 🤔. Reverting to `v12.10.0` works.

**Comment by kdenhartog** [comment]
Interesting, I believe the node-signatures-bbs library that's used underneath this is tested against node 14. I was recently looking into upgrading things and realized that Node 14 upgraded the V8 engine to a new major version. I believe the latest version of chromium browsers have updated as well to the new V8 engine. My hunch is that the compilation of the wasm files used are incompatible with this new engine and that's what's causing this issue. I've yet to dig deeper in to confirm it yet though.
