### ISSUE TITLE
TypeError: suite.ensureSuiteContext is not a function

### ISSUE THREAD

**Issue by smithbk** [mattrglobal/jsonld-signatures-bbs#140]
I'm just starting to use this library, so I'm probably doing something wrong but it is not obvious to me.  Thanks for any help.

Should the BbsBlsSignature2020 class extend suites.LinkedDataSignature rather than suites.LinkedDataProof, as it seems like that would fix my problem since the ensureSuiteContext function is defined in LinkedDataSignature which extends LinkedDataProof.

I am getting the following error with my sample app (see below):

```
TypeError: suite.ensureSuiteContext is not a function
    at Object.sign (/Users/keith/dev/agency/server/src/lib/node_modules/jsonld-signatures/lib/jsonld-signatures.js:61:9)
    at BBS.<anonymous> (/Users/keith/dev/agency/server/src/lib/bbs.js:65:66)
    at step (/Users/keith/dev/agency/server/src/lib/bbs.js:33:23)
    at Object.next (/Users/keith/dev/agency/server/src/lib/bbs.js:14:53)
    at /Users/keith/dev/agency/server/src/lib/bbs.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/keith/dev/agency/server/src/lib/bbs.js:4:12)
    at BBS.signDoc (/Users/keith/dev/agency/server/src/lib/bbs.js:57:16)
    at /Users/keith/dev/agency/server/src/lib/bbs.js:84:46
    at step (/Users/keith/dev/agency/server/src/lib/bbs.js:33:23)
```

Here is my sample app.

```
import { Bls12381G2KeyPair, BbsBlsSignature2020, BbsBlsSignatureProof2020, deriveProof } from "@mattrglobal/jsonld-signatures-bbs";
import { extendContextLoader, sign, verify, purposes } from "jsonld-signatures";

const purpose = new purposes.AssertionProofPurpose();

export class BBS {

    constructor() { }

    public async generateKeyPair(): Promise<Bls12381G2KeyPair> {
        return await Bls12381G2KeyPair.generate();
    }

    public async signDoc(keyPair: Bls12381G2KeyPair, doc: any): Promise<any> {
        const suite = new BbsBlsSignature2020({ key: keyPair });
        const opts = { suite, purpose };
        return await sign(doc, opts);
    }
}

async function main() {
    const bbs = new BBS();
    const kp = await bbs.generateKeyPair();
    const signedDoc = await bbs.signDoc(kp, inputDoc);
    console.log(`Signed doc: ${JSON.stringify(signedDoc)}`);
}

const inputDoc = {
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/citizenship/v1",
        "https://w3id.org/security/bbs/v1"
    ],
    "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
    "type": ["VerifiableCredential", "PermanentResidentCard"],
    "issuer": "did:example:489398593",
    "identifier": "83627465",
    "name": "Permanent Resident Card",
    "description": "Government of Example Permanent Resident Card.",
    "issuanceDate": "2019-12-03T12:19:52Z",
    "expirationDate": "2029-12-03T12:19:52Z",
    "credentialSubject": {
        "id": "did:example:b34ca6cd37bbf23",
        "type": ["PermanentResident", "Person"],
        "givenName": "JOHN",
        "familyName": "SMITH",
        "gender": "Male",
        "image": "data:image/png;base64,iVBORw0KGgokJggg==",
        "residentSince": "2015-01-01",
        "lprCategory": "C09",
        "lprNumber": "999-999-999",
        "commuterClassification": "C1",
        "birthCountry": "Bahamas",
        "birthDate": "1958-07-17"
    },
};

// tslint:disable-next-line: no-floating-promises
main();
```

**Comment by tplooker** [comment]
Hi @smithbk what version of jsonld-signatures are you using?

**Comment by smithbk** [comment]
"version": "9.0.2",
