### ISSUE TITLE
RuntimeError: unreachable in JEST

### ISSUE THREAD

**Issue by OR13** [mattrglobal/jsonld-signatures-bbs#144]
```text
 RuntimeError: unreachable

      at null.<anonymous> (wasm:/wasm/00198a2e:0:310816)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:343500)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:373122)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:369181)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:372526)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:359576)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:313825)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:368871)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:375715)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:132771)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:191919)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:342461)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:246814)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:334609)
      at null.<anonymous> (wasm:/wasm/00198a2e:0:316792)
      at _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6dd2715e80fa75d2 (wasm:/wasm/00198a2e:0:375455)
      at __wbg_adapter_32 (node_modules/@mattrglobal/jsonld-signatures-bbs/node_modules/@mattrglobal/bbs-signatures/lib/wasm.js:217:10)
      at real (node_modules/@mattrglobal/jsonld-signatures-bbs/node_modules/@mattrglobal/bbs-signatures/lib/wasm.js:202:20)
```
      
Observed when creating verifiable credentials of the form:

```js
{
'@context': [
  'https://www.w3.org/2018/credentials/v1',
  'https://w3id.org/security/suites/bls12381-2020/v1',
],
id: 'http://example.edu/credentials/3732',
type: ['VerifiableCredential'],
issuer: {
  id:
    'did:key:z5TcDVRemCWTd6qwxxhFeYDpQhK4pUYtuutodKP2MSDjzcqokf6cNCARsaF8JNZQ8FzWAYfFZbUqUCUDMWeWp8xVkRSr9z5Tf5k2tJgpjsqNM23E4VjHsCzN6WcSvLGKSA9VEMTc1d2F81mCCauerPY1VC8vPTkvtmEQZfmaZ54x15PJwbhkBxaEbydWjd7D2CWHbkFg9',
},
issuanceDate: '2010-01-01T19:23:24Z',
credentialSubject: { id: 'did:example:ebfeb1f712ebc6f1c276e12ec21' },
}
```

Version:

```
 "@mattrglobal/jsonld-signatures-bbs": "^0.10.1-unstable.3000f3c",
```

Interestingly NOT reproducible in JEST by itself, UNLESS you import a suite instance from another module, and don't import the suite directly... for example:

This passes
```ts
import { BbsBlsSignature2020 } from '@mattrglobal/jsonld-signatures-bbs';

 const result4 = await verifiable.presentation.verify({
    presentation: result3.items[0],
    format: ['vp'],
    challenge: '123',
    documentLoader: documentLoader,
    suite: verificationSuites,
  });

  console.log(BbsBlsSignature2020);
```

This fails
```ts
 const result4 = await verifiable.presentation.verify({
    presentation: result3.items[0],
    format: ['vp'],
    challenge: '123',
    documentLoader: documentLoader,
    suite: verificationSuites,
  });
```

I suspect this has something to do with how JEST imports handle wasm modules, or Uint8Arrays.

**Comment by OR13** [comment]
Indeed, this issue is caused by how jest handles globals... A work around is to use a custom environment:

`custom-jest-node-environment.js`
```js
const Environment = require('jest-environment-jsdom');
const { BbsBlsSignature2020 } = require('@mattrglobal/jsonld-signatures-bbs');

module.exports = class CustomTestEnvironment extends Environment {
  async setup() {
    await super.setup();
    if (typeof this.global.TextEncoder === 'undefined') {
      const { TextEncoder, TextDecoder } = require('util');
      this.global.TextEncoder = TextEncoder;
      this.global.TextDecoder = TextDecoder;
    }
    this.global.BbsBlsSignature2020 = BbsBlsSignature2020;
  }
};
```

`jest.config.js`
```js
module.exports = {
  // https://github.com/panva/jose/discussions/105
  // https://github.com/facebook/jest/issues/2549
  // Fixes jest bugs created by modifying globals...
  // ReferenceError: TextDecoder is not defined
  // RuntimeError: unreachable
  testEnvironment: "./custom-jest-node-environment.js",
};
```

**Comment by kdenhartog** [comment]
For reference, what version of jest are you running here? From what I remember jest has it's own import modules functionality rather than relying on node.js and I'm wondering if this issue is something that comes up because wasm modules haven't stablized with the new jest importer yet or if it's possibly because we haven't updated things yet. (I think we're 2 or 3 major versions behind in this repo at this point)

**Comment by OR13** [comment]
https://github.com/OR13/GNARLY/blob/main/package.json#L57

```
  "ts-jest": "^27.0.2",
```

**Comment by tplooker** [comment]
@OR13 do you know if this is still an issue, this library now uses ts-jest 28.0.1 and there have been multiple downstream updates to `@mattrglobal/bbs-signatures`

**Comment by OR13** [comment]
Let's close
