### ISSUE TITLE
yarn install gives 404 for @mattrglobal/node-bbs-signatures

### ISSUE THREAD

**Issue by geonnave** [mattrglobal/jsonld-signatures-bbs#35]
I downloaded the repo, run `yarn install`, and got `404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.5.0/node-v72-linux-x64.tar.gz`.

It seems my system is trying to download v72 when the available is v64, but I don't know why.

Here is the full output:

```
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.                                                                                                   
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⡀ @mattrglobal/node-bbs-signatures
[2/4] ⡀ sodium-native
[-/4] ⢀ waiting...
error /home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/@mattrglobal/node-bbs-signatures: Command failed.                                                                                            
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments:
Directory: /home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/@mattrglobal/node-bbs-signatures                                                                                                        
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@12.6.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/@mattrglobal/node-bbs-signatures/native/index.node" (not found)                                               
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.5.0/node-v72-linux-x64.tar.gz                                                                                        
node-pre-gyp http 404 https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.5.0/node-v72-linux-x64.tar.gz                                                                                        
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.5.0/node-v72-linux-x64.tar.gz                                           
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/node-pre-gyp/lib/install.js:142:27)                                                            
node-pre-gyp ERR! stack     at Request.emit (events.js:208:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/request/request.js:1059:10)                                                              
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:203:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)                                                                                                         
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:203:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
node-pre-gyp ERR! System Linux 4.19.0-8-amd64
node-pre-gyp ERR! command "/home/geovane/.nvm/versions/node/v12.6.0/bin/node" "/home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/@mattrglobal/node-bbs-signatures/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/geovane/dev/swarm/tmp/jsonld-signatures-bbs/node_modules/@mattrglobal/node-bbs-signatures                                                                                             
node-pre-gyp ERR! node -v v12.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
```

**Comment by kdenhartog** [comment]
I think this maybe because we built to use node v10 latest and the node version you use locally affects the uri that's constructed when downloading the script. Try using v10 latest for now and we'll work on getting support for newer versions of node.

@tplooker as far as I remember there weren't any constrains that kept us to having to use v10 for this package, so I think we should be able to add publishing the tarballs for different node versions. Do you see any concerns with this?

**Comment by geonnave** [comment]
Thanks, that worked.
In particular, I had to use `10.13.0`, as per this message: `error @typescript-eslint/eslint-plugin@2.28.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "10.0.0"`.

**Comment by kdenhartog** [comment]
We'll leave this issue open until we decide how to handle support for node 12 as well. Thanks for filing the issue.

**Comment by tplooker** [comment]
@geonnave correct our CI pipeline on each stable build creates a release for different OS's for [node-bbs-signatures](https://github.com/mattrglobal/node-bbs-signatures/releases). We just need to add your node abi to one that is built in this release process. As an interim solution if you have rust installed on your machine try installing one of our [unstable builds](https://www.npmjs.com/package/@mattrglobal/node-bbs-signatures) of node-bbs-signatures as this will compile the rust on your machine.

**Comment by kdenhartog** [comment]
@geonnave and @OR13 this should now be working for Node 12.

**Comment by tplooker** [comment]
@geonnave release [0.4.0](https://github.com/mattrglobal/jsonld-signatures-bbs/releases/tag/v0.4.0) and beyond should have this fix.
