### ISSUE TITLE
Unable to deriveProof due to getProofs not including proofValue

### ISSUE THREAD

**Issue by haardikk21** [mattrglobal/jsonld-signatures-bbs#76]
Attempting to `deriveProof` on a signed VC is failing due to `getProofs` returning an array of objects which only contains the `type` property - and ignoring the `proofValue` property which is required for `suite.deriveProof` with `BbsBlsSignatureProof2020`

Starting with this signed VC:
```json
{
        "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://www.w3.org/2018/credentials/examples/v1",
            "https://raw.githubusercontent.com/FlexFinTx/jsonld-contexts/master/contexts/nationalId.jsonld",
            "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
        ],
        "id": "http://example.gov/credentials/3732",
        "type": [
            "VerifiableCredential",
            "NationalIDCredential"
        ],
        "issuanceDate": "2020-03-10T04:24:12.164Z",
        "expirationDate": "2020-03-10T04:24:12.164Z",
        "credentialSubject": {
            "id": "did:flex:testnet:EiCHzIhOUeAdS3vjjdsIQ8v2CfXN935B7F6NIokzPJo_5g",
            "type": "NationalIDCredential",
            "nationalId": "9999999999",
            "givenName": "Haardik",
            "familyName": "Haardik",
            "gender": "Male",
            "birthDate": "1999-05-21",
            "address": "123 St, XYZ Avenue, Harare, Zimbabwe"
        },
        "issuer": "did:flex:testnet:EiD31RGW1u_FGmh4OK4WcQggSYsBKW98jYW8ev2njoyzwg",
        "proof": {
            "type": "https://w3c-ccg.github.io/ldp-bbs2020/context/v1#BbsBlsSignature2020",
            "created": "2020-08-31T07:42:14Z",
            "verificationMethod": "did:flex:testnet:EiD31RGW1u_FGmh4OK4WcQggSYsBKW98jYW8ev2njoyzwg#primary",
            "proofPurpose": "assertionMethod",
            "proofValue": "i8HrBN7DuLcmzban0c3TBHn956YI57kV+U3PrYMecalNckWjur5kWQO1tHIN0927M6gQ1jtLa3R9HodeA54HLUXCd6AyzCx+uh9qs7daex8Nzc7GxnGhXgZj+EkquvHBawMRuXk8P6H3MxAYSlk9jg=="
        }
    }
```

and the following `documentLoader`

```js
import fetch from "node-fetch";
import { extendContextLoader } from "jsonld-signatures";
import bbsContext from "./fixtures/lds-bbsbls2020-v0.0.json";
import jsonld from "jsonld";

export const documents = {
  "https://w3c-ccg.github.io/ldp-bbs2020/context/v1": bbsContext,
};

const getJson = async (url: string): Promise<any> => {
  return fetch(url, {
    headers: {
      Accept: "application/ld+json",
    },
    method: "get",
  }).then((data) => data.json());
};

const customDocLoader = (url: string): any => {
  if (url.startsWith("did:flex:testnet:")) {
    const didDocument = getJson(
      "https://testnet.sidetree.flexfintx.com/api/v1/" + url
    ).then(() => {
      return {
        contextUrl: null,
        document: didDocument,
        documentUrl: url,
      };
    });
  }

  const context = documents[url];

  if (context) {
    return {
      contextUrl: null, // this is for a context via a link header
      document: context, // this is the actual document that was loaded
      documentUrl: url, // this is the actual context URL after redirects
    };
  }

  return jsonld.documentLoaders.node()(url);
};

export default extendContextLoader(customDocLoader);
```

Calling `deriveProof` with a valid json-ld frame on this will result in a proof object which only contains `type`.

For simplicity of replication, running the following:
```js

  const getproofs = await getProofs({
    document: vc,
    documentLoader: documentLoader,
  });

  console.log("GP: ", getproofs);
```

returns 
```js
GP:  {
  proofs: [
    {
      '@context': 'https://w3id.org/security/v2',
      type: 'https://w3c-ccg.github.io/ldp-bbs2020/context/v1#BbsBlsSignature2020'
    }
  ],
  document: {
    '@context': 'https://w3id.org/security/v2',
    id: 'http://example.gov/credentials/3732',
    type: [
      'https://www.w3.org/2018/credentials#VerifiableCredential',
      'https://raw.githubusercontent.com/FlexFinTx/jsonld-contexts/master/contexts/nationalId.jsonld#'
    ],
    'https://www.w3.org/2018/credentials#credentialSubject': {
      id: 'did:flex:testnet:EiCHzIhOUeAdS3vjjdsIQ8v2CfXN935B7F6NIokzPJo_5g',
      type: 'https://raw.githubusercontent.com/FlexFinTx/jsonld-contexts/master/contexts/nationalId.jsonld#',
      'http://schema.org/address': '123 St, XYZ Avenue, Harare, Zimbabwe',
      'http://schema.org/birthDate': '1999-05-21',
      'http://schema.org/familyName': 'Haardik',
      'http://schema.org/gender': 'Male',
      'http://schema.org/givenName': 'Haardik',
      'http://schema.org/identifier': '9999999999'
    },
    'https://www.w3.org/2018/credentials#expirationDate': { type: 'xsd:dateTime', '@value': '2020-03-10T04:24:12.164Z' },
    'https://www.w3.org/2018/credentials#issuanceDate': { type: 'xsd:dateTime', '@value': '2020-03-10T04:24:12.164Z' },
    'https://www.w3.org/2018/credentials#issuer': {
      id: 'did:flex:testnet:EiD31RGW1u_FGmh4OK4WcQggSYsBKW98jYW8ev2njoyzwg'
    }
  }
}
```

This is a problem because `suite.deriveProof` expects the `proofs[0]` object to contain a `proofValue` (in the case of `BbsBlsSignatureProof2020`). Not being present is causing `deriveProof` to fail with 
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:331:9)
    at BbsBlsSignatureProof2020.deriveProof (/Users/haardikh/code/flex-ivapi/node_modules/@mattrglobal/jsonld-signatures-bbs/src/BbsBlsSignatureProof2020.ts:75:30)
    at Object.exports.deriveProof (/Users/haardikh/code/flex-ivapi/node_modules/@mattrglobal/jsonld-signatures-bbs/src/deriveProof.ts:46:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by haardikk21** [comment]
The problem was the original signed VC's `proof.type` being `https://w3c-ccg.github.io/ldp-bbs2020/context/v1#BbsBlsSignature2020` instead of just `BbsBlsSignature2020`
Closing.
